### ISSUE TITLE
A new app should have at least 1 qr template

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#106]
```
list index out of range
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/51.401199075546206538/rogerthat/pages/service_interact.py", line 59, in get
    qrtemplate, color = get_default_qr_template_by_app_id(si.app_id)
  File "/base/data/home/apps/s~mobicagecloudhr/51.401199075546206538/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/51.401199075546206538/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/51.401199075546206538/rogerthat/bizz/service/__init__.py", line 571, in get_default_qr_template_by_app_id
    qr_template = QRTemplate.get_by_key_name(app.qrtemplate_keys[0])
IndexError: list index out of range
```

**Comment by lucasvanhalst** [comment]
Create a default QR code template when creating an app

**Comment by lucasvanhalst** [comment]
Wait until this is properly spec'ed

**Comment by lucasvanhalst** [comment]
Use this one for all apps except for city apps: https://github.com/rogerthat-platform/rogerthat-backend/blob/master/src/rogerthat/bizz/qr-hand-only.png
Use this one for city apps: https://github.com/rogerthat-platform/rogerthat-backend/blob/master/src/rogerthat/bizz/qr-brand-oca.png

**Comment by lucasvanhalst** [comment]
Merged on staging branch
