### ISSUE TITLE
Can not load Veda's translations

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#182]
Veda > Store Listing > Translations

![screen shot 2017-07-11 at 15 09 03](https://user-images.githubusercontent.com/17762105/28069769-eafde25e-664a-11e7-954d-409b9d431444.png)

```
[Tue Jul 11 13:07:16 2017] [error] ERROR 2017-07-11 13:07:16,495 exception.py:135 Internal Server Error: /api/apps/ae-veda/metadata
[Tue Jul 11 13:07:16 2017] [error] Traceback (most recent call last):
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jul 11 13:07:16 2017] [error]     response = get_response(request)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jul 11 13:07:16 2017] [error]     response = self.process_exception_by_middleware(e, request)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jul 11 13:07:16 2017] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Tue Jul 11 13:07:16 2017] [error]     return view_func(*args, **kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
[Tue Jul 11 13:07:16 2017] [error]     return self.dispatch(request, *args, **kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
[Tue Jul 11 13:07:16 2017] [error]     response = self.handle_exception(exc)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
[Tue Jul 11 13:07:16 2017] [error]     self.raise_uncaught_exception(exc)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
[Tue Jul 11 13:07:16 2017] [error]     response = handler(request, *args, **kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/var/www/app-cfg/app_configurator/bizz/authentication.py", line 129, in _arguments_wrapper
[Tue Jul 11 13:07:16 2017] [error]     return view_method(request, *args, **kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/var/www/app-cfg/app_configurator/restapi/metadata.py", line 57, in get
[Tue Jul 11 13:07:16 2017] [error]     all_metadata = get_or_create_app_metadata(app)
[Tue Jul 11 13:07:16 2017] [error]   File "/var/www/app-cfg/app_configurator/bizz/metadata.py", line 89, in get_or_create_app_metadata
[Tue Jul 11 13:07:16 2017] [error]     metadata = get_language_metadata(app.app_id, language)
[Tue Jul 11 13:07:16 2017] [error]   File "/var/www/app-cfg/app_configurator/bizz/metadata.py", line 80, in get_language_metadata
[Tue Jul 11 13:07:16 2017] [error]     return AppMetaData.objects.get(app__app_id=app_id, language=language)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
[Tue Jul 11 13:07:16 2017] [error]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Tue Jul 11 13:07:16 2017] [error]   File "/opt/mobicage/app-cfg/venv/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
[Tue Jul 11 13:07:16 2017] [error]     (self.model._meta.object_name, num)
[Tue Jul 11 13:07:16 2017] [error] MultipleObjectsReturned: get() returned more than one AppMetaData -- it returned 2!
[Tue Jul 11 15:07:16 2017] [debug] mod_deflate.c(700): [client 192.168.150.7] Zlib: Compressed 27 to 28 : URL /api/apps/ae-veda/metadata, referer: https://gig-mobile-cc.appspot.com/apps/ae-veda/store-listing/translations
```

**Comment by abom** [comment]
@lucasvanhalst This shouldn't happen with new apps i think.
Can you do python manage.py shell to check which language metadata is duplicated?
Maybe something is wrong with the default metadata when created or so.

**Comment by lucasvanhalst** [comment]
I've purged one record from the database, let's close this and reopen if it happens again.
Duplicated language was 'en'. I'm going to try to add a unique constraint on language and app id so it doesn't happen again.

**Comment by lucasvanhalst** [comment]
Done and put online
